env:
  browser: true
  es2021: true
  node: true
extends: [standard-with-typescript, plugin:prettier/recommended]
ignorePatterns:
  - artifacts
  - typechain-types
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
