name: Yarn test

on:
  pull_request:
  workflow_dispatch:
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "20.5.0"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint:check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
